# Base docker-compose file
version: "1"

networks:
  cucumber: {}

services:
  cucumber-backend:
    hostname: cucumber-backend
    container_name: cucumber-backend
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: "yarn start"
    environment:
      NODE_ENV: development
      SERVICE_NAME: cucumber-backend
    ports:
      - 4200:4200
    labels:
      com.datadoghq.ad.logs: '[{"source": "cucumber-backend", "service": "cucumber-backend"}]'

  cucumber-frontend:
    hostname: cucumber-frontend
    container_name: cucumber-frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: "yarn start"
    environment:
      NODE_ENV: development
      SERVICE_NAME: cucumber-frontend
    ports:
      - 4200:4200
    labels:
      com.datadoghq.ad.logs: '[{"source": "cucumber-frontend", "service": "cucumber-frontend"}]'
